name: webview_flutter
description: A Flutter plugin that provides a WebView widget on Android and iOS.
version: 0.3.9+2
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=1.2.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.plugins.webviewflutter
    iosPrefix: FLT
    pluginClass: WebViewFlutterPlugin
